site_name: Documentation

pages:
    
    - Home: index.md
    - User Manual:
        - Warnings: warnings.md
        - Introduction: introduction.md
        - General: general.md
        - Hardware Setup: hardware-setup.md
        - Software: software.md
        - Spesifications: spesifications.md
        - Diagnostics: diagnostics.md
        - Helpful Links: helpful-links.md 