site_name: Documentation
site_url: 'https://waterlinked.github.io'
repo_url: https://github.com/waterlinked/waterlinked.github.io
theme:
    name: material
    theme_dir: docstheme/material
    logo: img/waterlinked_logo.png
    favicon: img/favicon_water_linked.ico
    palette:
        accent: blue
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/waterlinked/
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/waterlinked/
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCZFmOcapjyWgEnS_l6JgxQg/

markdown_extensions:
  - markdown.extensions.admonition
#  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta

extra_css:
    - css/extra.css

nav:
    - Home: index.md
    - Underwater GPS:
      - G2:
        - Quickstart: underwater-gps/quickstart.md
        - Introduction: underwater-gps/introduction.md
        - Topside:
          - Hardware: underwater-gps/hardware.md
          - Power supply: underwater-gps/power-supply.md
          - Network settings: underwater-gps/network-settings.md
        - Baseline:
          - Antenna: antenna.md
          - Receiver-D1: receiver-d1.md
        - Locator:
          - Locator-A1: locators/locator-a1.md
          - Locator-D1: locators/locator-d1.md
          - Locator-U1: locators/locator-u1.md
        - GUI:
          - Position: underwater-gps/gui/position.md
          - Baseline: underwater-gps/gui/receivers.md
          - Settings: underwater-gps/gui/settings.md
          - Diagnostic: underwater-gps/gui/diagnostic.md
          - Diagnostic report: underwater-gps/gui/diagnostic-report.md
          - Warnings: underwater-gps/gui/warnings.md
          - Demo GUI: underwater-gps/gui/demo-gui.md
        - Integration:
          - API: underwater-gps/integration/api.md
          - BlueROV2 integration: underwater-gps/integration/bluerov-integration.md
          - Code examples: underwater-gps/integration/code-examples.md
        - Software update: underwater-gps/sw-update.md
      - Explorer Kit:
        - Quickstart: explorer-kit/quickstart.md
        - Introduction: explorer-kit/introduction.md
        - Warnings: explorer-kit/warnings.md
        - Power supply: explorer-kit/power-supply.md
        - Network settings: explorer-kit/network-settings.md
        - Hardware: explorer-kit/hardware.md
        - Master-D1: master-d1.md
        - Receiver-D1: receiver-d1.md
        - Locators:
          - Locator-A1: locators/locator-a1.md
          - Locator-D1: locators/locator-d1.md
          - Locator-S1: locators/locator-s1.md
          - Locator-U1: locators/locator-u1.md
        - GUI:
          - Position: explorer-kit/gui/position.md
          - Receivers: explorer-kit/gui/receivers.md
          - Settings: explorer-kit/gui/settings.md
          - Diagnostic: explorer-kit/gui/diagnostic.md
          - API: explorer-kit/gui/api.md
        - Software Update: explorer-kit/upgrader.md
    - DVL:
      - DVL A50:
        - Introduction: dvl/dvl-a50.md
        - Details: dvl/dvl-a50-details.md
        #- Power supply: dvl/power-supply.md
        - IO Interface: dvl/io-interface.md
      - DVL A125:
        - Introduction: dvl/dvl-a125.md
        - Details: dvl/dvl-a125-details.md
        #- Power supply: dvl/power-supply.md
        - IO Interface: dvl/io-interface.md
      - GUI:
        - Dashboard: dvl/gui/dashboard.md
        - Diagnostic report: dvl/gui/diagnostic-report.md
        - Demo GUI: dvl/gui/demo-gui.md
      - Position: dvl/dead-reckoning.md
      - Integration:
        #- API: dvl/api.md
        - Protocol: dvl/dvl-protocol.md
        - BlueROV2 integration: dvl/bluerov-integration.md
      - Software update: dvl/sw-update.md
    - Modem:
      - Modem-M64:
        - Introduction: modem/modem-m64.md
        #- Details: modem/modem-m64-details.md
        #- Power supply: modem/power-supply.md
        #- IO Interface: modem/io-interface.md
      - Integration:
        - Protocol: modem/modem-m64-protocol.md

copyright: © Water Linked 2018-2021
